# Generated by Django 4.1.3 on 2022-12-07 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('initial_price', models.FloatField(verbose_name='Preço inicial')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='MyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('players', models.ManyToManyField(to='app.player', verbose_name='Jogadores')),
            ],
            options={
                'verbose_name': 'Meu time',
                'verbose_name_plural': 'Meus times',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('match_date', models.DateTimeField(verbose_name='Data do jogo')),
                ('team_a_goal', models.IntegerField(default=0, verbose_name='Gols do time A')),
                ('team_b_goal', models.IntegerField(default=0, verbose_name='Gols do time B')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_a_matches', to='app.team', verbose_name='Time A')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_b_matches', to='app.team', verbose_name='Time B')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('minutes', models.IntegerField(verbose_name='Minutos')),
                ('action', models.CharField(choices=[('goal', 'Gol'), ('assist', 'Assistência'), ('yellow card', 'Cartão amarelo'), ('red card', 'Cartão vermelho')], max_length=50, verbose_name='Ação')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.match', verbose_name='Jogo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.player', verbose_name='Jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Ação do jogo',
                'verbose_name_plural': 'Ações do jogo',
            },
        ),
    ]
