DROP TABLE IF EXISTS actions;
DROP TABLE IF EXISTS my_team_players;
DROP TABLE IF EXISTS my_team;
DROP TABLE IF EXISTS team_players;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS matches;





